# Default values for ethereum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent

# Node labels for pod assignment
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

bootnode:
  image:
    repository: ethereum/client-go
    tag: alltools-release-1.10

ethstats:
  image:
    repository: ethereumex/eth-stats-dashboard
    tag: latest
  webSocketSecret: my-secret-for-connecting-to-ethstats
  service:
    type: LoadBalancer

geth:
  image:
    repository: ethereum/client-go
    tag: release-1.10
  tx:
    # transaction nodes
    replicaCount: 2
    service:
      type: ClusterIP
    args:
      rpcapi: 'admin,debug,eth,miner,net,personal,shh,txpool,web3'
  miner:
    # miner nodes
    replicaCount: 3
  genesis:
    # geth genesis block
    difficulty: '0x01'
    gasLimit: '0x8000000'
    networkId: 7777
  account:
    # You will need to configure an Ethereum account before this
    # network will run. The Ethereum account will be used to seed
    # Ether and mined Ether will be deposited into this account.
    # ref: https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts
    address: '0x87bE88523441DC306E9576E485658efC63e50823'
    privateKey: '1fbaaf6ef1398d10878bf032054f4f0c239129eb32eed7e7b9c933d5e08f5970'
    secret: 'Eth.4TW!'
